### PR TITLE
an_navbar

### PR DESCRIPTION
**Pull request by alyssanycum**
## Description

Nav bar with Home, Employees, Departments, Computers, Training Programs, and Logout links

## How do I access this branch?

git checkout master
git fetch --all
git checkout an_navbar

***make sure your dev tools are open***

## Motivation and Context

#19 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MReeds** [comment]
All links work great but when you select logout you are still presented with a logout link. Try setting it to flip to a login when signed out

**Comment by keithrpotempa** [comment]
Praise you! Excellent work, Alyssa. What a dream to navigate this site now!

**Comment by alyssanycum** [comment]
Good call Matt! I will wait to merge this till tomorrow then so I can fix that in the morning.

**Comment by alyssanycum** [comment]
If a user is logged in, the logout button should appear in the navbar. If a user is logged out, the login button should appear in the navbar.

git checkout master
git fetch --all
git checkout an_navbar
git pull

**Comment by keithrpotempa** [comment]
Yeah, for some reason, I'm getting an error on login:
`login() missing 1 required positional argument: 'user'`

**Comment by alyssanycum** [comment]
merged in Keith's code and fixed login

git pull on my branch and try again!

**Comment by keithrpotempa** [comment]
That fix did it! Awesome, Alyssa.

**Comment by MReeds** [comment]
Works great!!

**Pull request merged**
