### PR TITLE
Kp readme

### PR DESCRIPTION
**Pull request by keithrpotempa**
## Description

- README.md updated to conform with present project details 
- deleted the sqlite backup file

## How do I access this branch?

- NO PULLING NECESSARY
- Go here in the browser: https://github.com/nss-day-cohort-38/bangazon-workforce-management-aquarii-star-system/tree/kp-readme
- Scroll down and look at the readme.

## Motivation and Context

We need a readme!

## How Has This Been Tested?

I've looked at it with my own eyes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alyssanycum** [comment]
Looks good Keith! Thanks for doing this for the team :)

I just have one more edit - departments doesn't have delete functionality, just read and create

**Comment by jcksnparsons** [comment]
There is no delete functionality for employees. Looks good otherwise!

**Comment by MReeds** [comment]
Computers do not have an update functionality

**Comment by keithrpotempa** [comment]
Updated based on y'all's comments. Much appreciated!

Also, sorry, Matt!

**Pull request merged**
