### PR TITLE
Mr computers list

### PR DESCRIPTION
**Pull request by MReeds**
Added a list view with links to individual details that includes a delete button. Also a functioning form to add a new computer.
## How do I access this branch?

git checkout master
git fetch --all
git checkout MR-computersList

## Motivation and Context

#9 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by keithrpotempa** [comment]
Computer List and Details look like they're working great! Solid work.  

The form is getting me a multi dict error for `decommission_date` when I submit it.

P.S. I had to do migrations. Might be helpful to include in the instructions:
```
python manage.py makemigrations
python manage.py migrate
```

**Comment by alyssanycum** [comment]
I'm getting the same error as Keith. 

I also just saw this in your ticket - "the computer should be deleted only if it is has never been assigned to an employee" 

^so we'd still need to add that functionality

**Comment by alyssanycum** [comment]
Form error is fixed! We'll circle back to the delete

**Comment by keithrpotempa** [comment]
This looks good to me! Make a note to circle back to the conditional delete part.

**Pull request merged**
